### ISSUE TITLE
DatePlaceholders get only replaced in Action

### ISSUE THREAD

**Issue by JensSpanier** [TechieGuy12/FileWatcher#21]
I was trying to use `[currentdate:...]` in `<arguments>`. Because it wasn't working I looked into the code and saw that `ReplaceDatePlaceholders` is only located in `Action`.

Would it be possible to replace DatePlaceholders like the other placeholders (e.g. in `ReplacePlaceholders`)?

**Comment by TechieGuy12** [comment]
I can look at adding the date replacements in the other sections, as well.

**Comment by TechieGuy12** [comment]
The DatePlaceholders is now available for all changes that can use the path placeholder action. The [latest release](https://github.com/TechieGuy12/FileWatcher/releases/latest) is available with this change.

**Comment by JensSpanier** [comment]
Just tried the new version. Works great. Thank you very much!
