### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by ericxin1982** [TechieGuy12/FileWatcher#32]
Hi @TechieGuy12 

Thanks for providing this good tool.

The notification can access these abbreviations for post/get to endpoint or not.
Not sure, but I have use case to send notification about which specific file added.

Thanks
Eric Xin

[exactpath] - full path of the changed file
[fullpath] - full path of the changed file without the path of the watch
[path] - the path of the changed file without the path of the watch and the file
[file] - the name of the file with the extension
[filename] - name of the file without the extension
[extension] - the file extension

**Comment by TechieGuy12** [comment]
I will add the placeholders to the notifications as well.

**Comment by ericxin1982** [comment]
Thanks

**Comment by ericxin1982** [comment]
@TechieGuy12 Sorry, Just wondering when this can be released, or there is no plan yet.

**Comment by ericxin1982** [comment]
Ok, let me try, thanks.
