### ISSUE TITLE
need step

### ISSUE THREAD

**Issue by ericxin1982** [TechieGuy12/FileWatcher#45]
Hi @TechieGuy12 

I saw the new doc in wiki, and I am not sure how the need works, like generate the check sum, the further step needs the checksum value from generate check sum step or how to reflect this need.

https://github.com/TechieGuy12/FileWatcher/wiki/Steps

Thanks
Eric Xin

**Comment by TechieGuy12** [comment]
The needs works by specifying the ID of the step that is required to complete with the `need` element.

In the example in the wiki link, the `create-picture-plex-refresh-library` step requires the `create-picture-get-checksum` step to complete before it can run.

To accomplish this, the `create-picture-get-checksum` is specified in the `need` element of the `create-picture-plex-refresh-library` step.

**Comment by ericxin1982** [comment]
Ok, I see.
